# Generated by Django 4.2.5 on 2023-12-24 23:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="uuid",
        ),
        migrations.AddField(
            model_name="invoice",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reference_pk",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("standby", "Standby"),
                    ("passed", "Passed"),
                    ("passed_with_warnings", "Passed with warnings"),
                    ("rejected", "Rejected"),
                    ("error", "Error"),
                ],
                default="standby",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="InvoiceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("change_invoice_code", "Change Invoice Code"),
                            ("reject_invoice", "Reject Invoice"),
                        ],
                        default="change_invoice_code",
                        max_length=255,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "invoice_code",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("debit", "debit"),
                            ("credit", "credit"),
                        ],
                        max_length=255,
                    ),
                ),
                ("qrcode", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("standby", "Standby"),
                            ("passed", "Passed"),
                            ("passed_with_warnings", "Passed with warnings"),
                            ("rejected", "Rejected"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=255,
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
