# Generated by Django 4.2.5 on 2024-01-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_alter_invoicehistory_invoice_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="uid",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoicehistory",
            name="uid",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
