# Generated by Django 4.2.5 on 2024-01-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_invoice_uid_invoicehistory_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_code",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice"),
                    ("credit", "credit"),
                    ("debit", "debit"),
                ],
                default="invoice",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="invoicehistory",
            name="invoice_code",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice"),
                    ("credit", "credit"),
                    ("debit", "debit"),
                ],
                max_length=255,
            ),
        ),
    ]
