# Generated by Django 4.2.5 on 2024-01-26 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0005_alter_invoice_invoice_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_code",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice"),
                    ("credit", "credit"),
                    ("debit", "debit"),
                ],
                db_index=True,
                default="invoice",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("simplified", "Simplified"), ("standard", "Standard")],
                db_index=True,
                default="simplified",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("10", "Cash"),
                    ("30", "Credit"),
                    ("42", "bank_account"),
                    ("48", "bank_card"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("standby", "Standby"),
                    ("passed", "Passed"),
                    ("passed_with_warnings", "Passed with warnings"),
                    ("rejected", "Rejected"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="standby",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="uid",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["id", "account"], name="invoices_cu_id_0a26d1_idx"
            ),
        ),
    ]
