# Generated by Django 4.2.5 on 2024-01-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "invoices",
            "0006_alter_invoice_created_at_alter_invoice_invoice_code_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoicehistory",
            old_name="invoice_date",
            new_name="created_date",
        ),
        migrations.AddField(
            model_name="invoice",
            name="shared_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="invoicehistory",
            name="shared_date",
            field=models.DateTimeField(null=True),
        ),
    ]
