# Generated by Django 4.2.5 on 2024-11-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0007_rename_invoice_date_invoicehistory_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="document_type",
            field=models.CharField(
                choices=[("invoice", "Invoice"), ("offer", "Offer")],
                db_index=True,
                default="invoice",
                help_text="Determines if this is a regular invoice or an offer price quote",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="valid_until",
            field=models.DateField(
                blank=True,
                help_text="Date until which the offer price is valid, when the document type is an offer",
                null=True,
            ),
        ),
    ]
