# Generated by Django 4.2.5 on 2024-11-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0008_invoice_document_type_invoice_valid_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicehistory",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("change_invoice_code", "Change Invoice Code"),
                    ("change_document_type", "Change Document Type"),
                    ("reject_invoice", "Reject Invoice"),
                ],
                default="change_invoice_code",
                max_length=255,
            ),
        ),
    ]
