# Generated by Django 4.2.5 on 2023-12-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
