# Generated by Django 4.2.5 on 2024-01-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_package_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="zatca_related",
            field=models.BooleanField(
                default=False,
                help_text="If true, the package will be related to ZATCA usage",
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="package_zatca_related",
            field=models.BooleanField(default=False),
        ),
    ]
