# Generated by Django 4.2.5 on 2024-01-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_package_zatca_related_paymenthistory_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("completed", "completed"),
                    ("not_active", "Not Active"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
