# Generated by Django 4.2.5 on 2024-01-10 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_paymenthistory_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="duration",
            field=models.IntegerField(
                help_text="Duration in months",
                validators=[
                    django.core.validators.MaxValueValidator(
                        6, "Maximum duration is 6 months"
                    )
                ],
            ),
        ),
    ]
