# Generated by Django 4.2.5 on 2024-01-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_paymenthistory_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="discount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
