# Generated by Django 4.2.5 on 2024-01-26 16:17

import accounts.services.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_paymenthistory_discount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="account",
            name="tax_number",
            field=models.CharField(
                db_index=True,
                max_length=15,
                null=True,
                validators=[
                    accounts.services.validators.NumericLengthValidator(
                        field_name="Tax Number", length=15
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("completed", "completed"),
                    ("not_active", "Not Active"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
