# Generated by Django 4.2.5 on 2024-11-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_account_options_alter_account_tax_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="duration",
            field=models.IntegerField(help_text="Duration in months"),
        ),
    ]
